server:
  port: 80
spring:
  data:
    elasticsearch:
      cluster-name: ENC(gaBqGWoAcof4a4L7MMojxdiaxTeAf5qyZOyoxmrvfek=)
      cluster-nodes: 182.92.81.132:9300 # 程序连接es的端口号是9300
  datasource: # 设置数据库相关
    url: jdbc:mysql://182.92.81.132/yiqianLibrary?characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(7Kcv4fPB3xlPI+UgtA8GYL2Cp/MSzQ7A)
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时⻓(毫秒)，超时而且没被使用则被释放 (retired)，缺省:30分钟，建议设置比数据库超时时⻓少30秒，参考MySQL wait_timeout参数(show variables like '%timeout%';)
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值:10; 推荐的公式:((core_count * 2) + effective_spindle_count)
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: lq.yiqian.domain
  configuration:
    map-underscore-to-camel-case: true

  #jasypt: # 项目使用jasypt加密
  #  encryptor:
  #    password: 盐值建议不要在配置文件中配置, 配置到环境变量或者启动参数中, jasypt.encryptor.password=***

jetcache:
  # 控制台输出统计数据，统计间隔（单位分钟），0表示不统计
  statIntervalMinutes: 60
  # 是否加入缓存key前缀
  areaInCacheName: true
  local:
    default:
      # 缓存类型。linkedhashmap、caffeine为当前支持的本地缓存类型
      type: linkedhashmap
      # Key的转换器
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      # 缓存类型。tair、redis为当前支持的远程缓存
      type: redis
      keyConvertor: fastjson
      # 采用Java序列化存储
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 182.92.81.132
      port: 6378
#      password: red-qian